// 测试注册表（属性检定板块，仿 tools/registry.js：新增测试 = 加条目 + 建页面）
//
// 注意：norm 字段必须如实标注参考分布来源与局限（数据红线见 docs/架构决策.md #16）。
export const tests = [
  {
    slug: 'reaction-time',
    title: '视觉反应',
    desc: '屏幕变绿的瞬间点击，5 轮取中位数',
    icon: 'visibility',
    tags: ['反应速度', '反应时间', '手速'],
  },
  {
    slug: 'choice-reaction',
    title: '选择反应',
    desc: '四个方块随机亮起，点对亮的那个',
    icon: 'filter_alt',
    tags: ['反应速度', '抑制控制', '选择'],
  },
  {
    slug: 'digit-span',
    title: '数字广度',
    desc: '数字闪现后按顺序复现，测工作记忆容量',
    icon: 'timeline',
    tags: ['工作记忆', '记忆', '数字'],
  },
  {
    slug: 'auditory-reaction',
    title: '听觉反应',
    desc: '听到提示音的瞬间点击，5 轮取中位数',
    icon: 'volume_up',
    tags: ['反应速度', '听觉', '声音'],
  },
  {
    slug: 'stroop',
    title: 'Stroop 干扰',
    desc: '按字的颜色选择，无视字义干扰',
    icon: 'palette',
    tags: ['干扰抑制', '注意力', '颜色'],
  },
  {
    slug: 'visual-search',
    title: '视觉搜索',
    desc: '在一堆干扰符号中找出唯一目标',
    icon: 'grid_view',
    tags: ['注意力', '目标搜索', '视觉'],
  },
  {
    slug: 'time-perception',
    title: '时间感知',
    desc: '不看钟，凭感觉估出目标时长后停止',
    icon: 'schedule',
    tags: ['时间感知', '内部时钟', '估计'],
  },
  {
    slug: 'mental-rotation',
    title: '心理旋转',
    desc: '判断旋转后的图形是同一个还是镜像',
    icon: 'rotate_right',
    tags: ['空间能力', '旋转', '心理旋转'],
  },
  {
    slug: 'n-back',
    title: 'N-back 记忆',
    desc: '当前字母是否与 2 步前相同？测工作记忆更新',
    icon: 'repeat',
    tags: ['工作记忆', 'N-back', '更新'],
  },
  {
    slug: 'number-series',
    title: '逻辑推理',
    desc: '找出数列规律，选出下一个数',
    icon: 'quiz',
    tags: ['逻辑', '推理', '数列'],
  },
  {
    slug: 'risk-preference',
    title: '风险偏好',
    desc: '确定的小奖还是五五开的大奖？六道选择题',
    icon: 'casino',
    tags: ['风险', '决策', '偏好'],
  },
  {
    slug: 'task-switching',
    title: '任务切换',
    desc: '规则随机切换：按奇偶或按元音分类，测切换成本',
    icon: 'alt_route',
    tags: ['认知灵活性', '切换', '执行'],
  },
  {
    slug: 'spatial-memory',
    title: '空间记忆',
    desc: '色块闪现的位置和顺序，凭记忆复现',
    icon: 'view_module',
    tags: ['空间记忆', 'Corsi', '位置'],
  },
  {
    slug: 'delay-gratification',
    title: '延迟满足',
    desc: '立即拿小积分，还是等待换大积分？',
    icon: 'hourglass',
    tags: ['延迟满足', '自制力', '等待'],
  },
  {
    slug: 'aim-trainer',
    title: '手眼精度',
    desc: '目标点随机出现，尽快点掉，30 秒极限',
    icon: 'ads_click',
    tags: ['手眼协调', '瞄准', '精准'],
  },
  {
    slug: 'mental-math',
    title: '心算速度',
    desc: '连续加减乘，看你的数学流畅性',
    icon: 'calculate',
    tags: ['心算', '数学', '计算'],
  },
  {
    slug: 'color-vision',
    title: '色觉辨别',
    desc: '色块中藏了一个异色块，逐级变难',
    icon: 'contrast',
    tags: ['色觉', '颜色', '辨别'],
  },
];
